### ISSUE TITLE
How to run polyfill in development and production?

### ISSUE THREAD

**Issue by pindiespace** [vigetlabs/blendid#388]
I've been configuring gulp-starter to handle a conditional polyfill load, in the form:

Because webpack needs Promises to run, and most setups always load a Promise polyfill - despite the fact that more and more browsers don't need it, so it is wasted code. 

I want to conditionally Promise polyfill separately from the others dynamically, with an explicit <script> tag and a loader script like described below.:

https://philipwalton.com/articles/loading-polyfills-only-when-needed/

The idea is to load the Promise (and Server-Sent events) index.html, then execute the main() function after they are loaded, so Webpack works. In main(), other polyfills might be loaded from a separate polyfill file. This strategy avoids having all browsers (even those with Promise and Server-Sent Events) from having to load polyfills required by Webpack.

I tried a simple approach, where I split the code between app and polyfill. Using the example: 

```
( function loadScript( src ) {
  var js = document.createElement( 'script' );
  js.src = src;
  js.onload = function () {
    done();
  };
  js.onerror = function () {
    done( new Error( 'Failed to load script ' + src ) );
  };
  document.head.appendChild( js );

  function done ( err ) {
  
      if ( err ) {

        if (err ) console.log( err );

       // load other stuff, including other polyfills if desired.
      main(); //entry to app, which might load other polyfills.

      }
    console.log( 'all done' );

  }
} ) (' './promise.js' );

```

When I use gulp-starter in production mode, it works fine - the libraries are copied to the /js folder and recognized. However...I can't get it to work in development - the server complains it can't find my promise.js. Since there isn't anything in public/js during development, this isn't surprising.

What would be the best strategy with gulp-starter to...

1. Conditionally load Promise and Server-Side events polyfills at runtime using old-school onload events. These would be separate, and not in any file loaded or used by webpack.

2. When this is complete, load a function main() which is the start of the app code, with Webpack code split with additional polyfills into polyfills.js

3. Set it up so things work in both development (where there is nothing in public/js ) and production mode (where public/js exists).

**Comment by synapticism** [comment]
This is a bit unrelated... but since I've tackled this same issue for a similar project I thought I may as well chime in even if I don't have a specific suggestion for point 3. My current setup involves three files: the initial loader, the polyfill bundle, and the app. The loader includes Modernizr so I can test for Promises (and a bunch of other stuff); if the browser isn't fully supporting whatever the requirements are [loadjs](https://github.com/muicss/loadjs) will request the polyfill bundle and then load the app bundle in a callback (or just load the app if everything is cool). Maybe it's a bad idea but I prepare all three bundles with Webpack since, if I'm not mistaken, Promises aren't required until you're using code-splitting... but it wouldn't be hard to bundle polyfills and your loader separately.

**Comment by greypants** [comment]
Closing, since seems like @synapticism answered this, and it's not directly related to this package.
