### ISSUE TITLE
Blendid and CraftCMS — struggling with javascript and production

### ISSUE THREAD

**Issue by schikulski** [vigetlabs/blendid#403]
Hi! I've read through the [Blendid Craft guide in the wiki](https://github.com/vigetlabs/gulp-starter/wiki/Craft-Setup) and installed the [gulprev plugin](https://github.com/vigetlabs/gulp-starter/tree/master/extras/craft). SASS and template reloading are working fine in development, but I've run into two problems:

**Javascript won't get included in development**
When running `yarn run blendid` browserSync doesn't seem to include the javascript. And the js console doesn't show any of the console.log from `src/javascripts/app.js`. So to me it looks like JS isn't being included at all.

**`yarn run blendid -- build` builds both js and css, but how should I include them in my template?**
After running `yarn run blendid -- build` I get the file `public/assets/dyn/css/app-hash.css` and `public/assets/dyn/js/app-hash.js`. I'm including the CSS in my template file as `{{ 'assets/dyn/css/app.css' | gulp_rev }}`. While this works in development, in production the layout are not adding the hash to the filename, making the style not showing in the browser. And how should I add the javascript hashed app.js file in my template?

**Comment by Bshally** [comment]
I'm having the same issue with the js, and haven't gotten past that point myself. I'll try fiddling with it and post any solutions I come to.

**Comment by Bshally** [comment]
Busted about an hour checking out the docs and trying to find where webpack was putting the things it was building, no dice.

**Comment by CosminAnca** [comment]
> Javascript won't get included in development
When running yarn run blendid browserSync doesn't seem to include the javascript. And the js console doesn't show any of the console.log from src/javascripts/app.js. So to me it looks like JS isn't being included at all.

@schikulski Try adding the following to `javascript` object inside `task-config.js`:
`publicPath: "/path/to/destination/folder/containing/javascipts/"`

**Comment by Bshally** [comment]
Thanks. I'll try this when I get back to the office.

**Comment by Bshally** [comment]
@CosminAnca, Thanks, that seems to have gotten closer to solving the issue. I've added that line config object and this has allowed me to call the js from where I would expect it to be, both from the `yarn run blendid` and `yarn run blendid --build` commands. Still, the issue of the js files not being placed within the defined destination directory remains, even upon build. Any suggestions on what to try next? My task-config.js & path-config.json are included in the screenshot below, including what the project structure looks like. I'll be digging into the Webpack docs, but help is  definitely appreciated. 


<img width="1700" alt="screen shot 2017-03-24 at 2 31 38 pm" src="https://cloud.githubusercontent.com/assets/3440317/24308555/c11c5f76-109e-11e7-8c33-ab0f3ce831ab.png">

**Comment by Bshally** [comment]
Welp, I just realized that I was messing up my build task, and that is why the js files were not being output. I was running it with `--build` instead of `-- build`. Now I get everything showing up for production. 

@schikulski , try adding that line in from CosminAnca above, that got the resources working for me in development. You can either call them using a script tag pointing at where the js files should be using the rev plugin, or you can use the [includejsfile tag[(https://craftcms.com/docs/templating/includejsfile) with it as well. I haven't gotten this far, and personally haven't looked into what asset revision does and why it is useful yet. I'm just disabling it to get my project set up without it for now.  Like Addy Osmani says: "First do it, then do it right, then do it better" !

I'll add this info to the guide in the wiki.

**Comment by Bshally** [comment]
This may be ready to close, @greypants .
