### ISSUE TITLE
[Question] How to add pixrem to additionalTask

### ISSUE THREAD

**Issue by dennzimm** [vigetlabs/blendid#426]
Hi, 
I do not know if it is the right place for a question, but: 

can you give me a tip how to add e.g. [pixrem](https://www.npmjs.com/package/pixrem) as an addition task? I've tried to add it, but it does not work.

Same problem with [postcss-flexibility](https://github.com/7rulnik/postcss-flexibility).
I've tried to add it, but it does not work...

Can you give me an example of how both could work?

**Comment by benjtinsley** [comment]
@dennzimm since you would like to use PostCSS, would need to use the [`alternateTask` option](https://github.com/vigetlabs/blendid/wiki/Configuration#alternatetask) in your task-config.js file to define a PostCSS specific task.

from there, you can require pixrem and postcss-flexibility at the top of the file and reference them within the plugins array. you may need to [reuse some of the methods](https://github.com/vigetlabs/blendid/blob/master/gulpfile.js/tasks/stylesheets.js#L29-L38) set in the stylesheets task to ensure it works with the existing tasks, however.
