### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [vigetlabs/blendid#572]
Hi, what is the status of this project? Is it still actively maintained?

**Comment by besimhu** [comment]
I believe with @greypants moving on, the project itself has come to a halt. I haven't seen any updates in a very long time, and I have taken the code base and adjusted for my own needs over time. 

I would also say with the increase in webpack + SPA based frameworks, there has been much less of a need for the build system offered by blendid. Static websites can be created with gatsby or vuepress these days. 

There is much debate on whether you should mix gulp + webpack. Even though gulp makes it easier to create and manage tasks compared to npm-scripts, it is significantly harder to do the same in a webpack process. I have started my own set of build tools that uses webpack for everything, but webpack itself is not made to handle tasks. It's a bundler which it does really well. 

At the end of the day, there have been a lot of improvements and best practices on how to do build scripts today. I am toying around with a simplified gulp4 + webpack for javascript approach for my own freelance.

**Comment by olets** [comment]
@DanielRuf @besimhu a long-overdue update:

Yes greypants is still a close friend of the Blendid family but is now focusing on other projects.

In this extended period of outward dormancy, Blendid has been very much alive. The @viget team uses it in production on _many_ projects. That requires a level of reliability that's been both good and bad for OS: you can count on it working and being maintained, but the pace of development is conservative.

We've been working to carve out some more time for Blendid community management (sincere apologies to those folks who've waited a long time for issue responses 😞💝) and updates. The landscape has changed certainly since Blendid appeared, notably with Parcel providing a solid option for blank-slate work, but there's a place for a very lightly opinionated build tool with a reasonable OOB configuration.

Near term: With 4.5.0 we're just about caught up with dependency updates (just need knock out the #578 refactor). The goal is to get through the open PRs and also merge in various tweaks to support the way the core team uses Blendid lately (woohoo PostCSS without an alternate stylesheets task at last!)

Longer term: We've also been experimenting with building tools that cut out the taskrunner layer. Since the "Blendid" project isn't tied to a specific specific underlying implementation, you may see that in a future version. But then again, for now Gulp _is_ really nice for running tasks

**Comment by olets** [comment]
Well folks, the time has come. The Viget team is no longer actively maintaining Blendid a824ce4. If you're interested in taking it on, get in touch.

This of course does not mean it will suddenly stop working. Viget does still have projects running on Blendid. It's stable and has been feature-complete for Viget's internal needs for quite a while. It's still a great plug-and-play solution.

The next generation of Viget's internal tooling may some day go public, and if it does we hope you'll try it out. If you haven't yet, check out the YAML, PostCSS, and Twig enhancements since we last talked (https://github.com/vigetlabs/blendid/releases). I personally have been playing with Gulp again recently, and for the time being am calling dibs on 578. We'll see, so many interesting things out there to work on!

**Comment by rarous** [comment]
If you are interested, we are maintaining Blendid fork at https://github.com/topmonks/blendid. It incorporates work done on Blendid 5 branch as many other PRs. But it diverged a lot during the time. We switched from webpack to rollbar, updated to Node 14, Gulp 4 and Dart Sass and added many new features.
